# Generated by Django 3.2.20 on 2023-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='name',
        ),
        migrations.AddField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Artwork title'),
        ),
    ]
