# Generated by Django 3.2.20 on 2023-08-17 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(default='../default_profile_qpd7ju', upload_to='images/')),
                ('location', models.CharField(max_length=255)),
                ('influences', models.TextField()),
                ('art_image1', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
                ('art_image2', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
                ('art_image3', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.medium')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.style')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
