# Generated by Django 3.2.20 on 2023-08-24 16:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('influences', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on:')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited on:')),
            ],
            options={
                'verbose_name': ('Artist',),
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='art image')),
                ('art_image_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Artwork name')),
                ('alt_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Alt text')),
                ('actual_date_of_creation', models.DateTimeField(blank=True, null=True, verbose_name='Created on:')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Added on:')),
                ('edited_date', models.DateTimeField(auto_now_add=True, verbose_name='Edited on:')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
            options={
                'verbose_name': 'Artwork',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='medium',
            field=models.ManyToManyField(to='artists.Medium'),
        ),
        migrations.AddField(
            model_name='artist',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='style',
            field=models.ManyToManyField(to='artists.Style'),
        ),
    ]
