# Generated by Django 3.2.20 on 2023-08-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('art_image1', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
                ('art_image2', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
                ('art_image3', models.ImageField(default='../default_post_vnjiii', upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='art_image1',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='art_image2',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='art_image3',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='artistwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artistwork'),
        ),
    ]
