# Generated by Django 3.2.20 on 2023-08-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20230824_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='medium',
            field=models.ManyToManyField(blank=True, to='artists.Medium'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='style',
            field=models.ManyToManyField(blank=True, to='artists.Style'),
        ),
    ]
