# Generated by Django 3.2.20 on 2023-08-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20230829_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
